### ISSUE TITLE
Conflict with CaveBiomesApi

### ISSUE THREAD

**Issue by KKotik** [KdotJPG/Simply-Improved-Terrain#11]
When CaveBiomesApi 1.1.0 installed with Simply Improved Terrain some conflicts happens.
Like terrain starting to be flat and missing water even in oceans.
![image](https://user-images.githubusercontent.com/45950781/124030872-4906c380-d9ff-11eb-9400-c50f678491ac.png)
![image](https://user-images.githubusercontent.com/45950781/124030883-4dcb7780-d9ff-11eb-9d23-72958fea54ab.png)
![image](https://user-images.githubusercontent.com/45950781/124030900-53c15880-d9ff-11eb-95d3-58f4294265dd.png)
![image](https://user-images.githubusercontent.com/45950781/124030923-5cb22a00-d9ff-11eb-8fed-93960881ca9c.png)

**Comment by KdotJPG** [comment]
Hmm... this could be related to the changes Cave Biome API applies in order to get the 3D overworld biomes. Simply Improved Terrain [looks at y=0](https://github.com/KdotJPG/Simply-Improved-Terrain/blob/Fabric-1.17/src/main/java/jpg/k/simplyimprovedterrain/biome/CachedScatteredBiomeAccessType.java#L71) to determine the biome used for 2D blending (mirrored from Vanilla, where Y coordinate doesn't matter in the 2D biome lookup). Cave Biome API [changes some things to look at y=64 instead](https://github.com/ItsBlackGear/CaveBiomeAPIFabric/blob/f391ec232ca6e132a9b21b52fa6072a393ecff7f/src/main/java/com/alphastudios/cavebiomeapi/mixin/BiomeAccessMixin.java#L23).

Going to see if it's as simple as changing this value in Simply Improved Terrain. Thanks for the report!

**Comment by KKotik** [comment]
How things are going? Could it be better to check biomes from the middle or top point of the world instead. For safety.

**Comment by KdotJPG** [comment]
I think I'll first try sampling from y=64 like Cave Biomes does. I've had a number of things to bounce between the past few days, but I do want to get this resolved! I'm going to test a number of mod pairings to be certain before pushing the update with this change, but I don't currently forsee it'll cause any issues.

**Comment by KdotJPG** [comment]
It fixed the issue, but another showed up.

Before:
![](https://user-images.githubusercontent.com/8829856/125003342-065b7180-e025-11eb-8730-1383db861771.png)

After:
![](https://user-images.githubusercontent.com/8829856/125003354-0b202580-e025-11eb-8797-23401f986531.png)

Also FWIW the land issue seems to not be present in Cave Biomes 2.0, only 1.1. With 2.0, I get the discolored surface patches, but oceans aren't turned into land, regardless of whether I change to y=64 in the biome lookup.

Going to keep looking into this.

**Comment by KKotik** [comment]
Cave Biomes 2.0 is old versiong. A bit confusing, but 1.1 is latest. Next update author will fix biome colors, this issue seems to be on other mod side.

**Comment by KKotik** [comment]
I think the issues is fixed, only what was happening from SIT side was terrarin generation. The biome coloring missing even in CaveBiomesApi itself, you could test it out without any other mods, to make sure and understand what I am talking about.

**Comment by KKotik** [comment]
Fabric verison of CaveBiomeApi already have update that already fixed it according to changelog of 1.2. It's only need to be ported to forge. (Still confusing that in changelog it says 2.0, but it's 1.2)

 ![image](https://user-images.githubusercontent.com/45950781/125066740-065a8080-e0bc-11eb-9294-fac012308f7c.png)

**Comment by ItsBlackGear** [comment]
my bad 👀 i forgot to rename it to 1.2

**Comment by KKotik** [comment]
CaveBiomesApi just released new version (1.2.0) that should fix that biome coloring issue.

**Comment by rVanix** [comment]
I have the same or a similar issue like there are no oceans or rivers in the world its just grass allover and it says its the ocean biome for example bu it's just green all over the place.

**Comment by KKotik** [comment]
There is an update happened to CaveBiomesApi and Caves And Cliffs backport. So people will massively report it and deal with.

**Comment by KKotik** [comment]
Hello, I saw updates on Fabric version recently. How thing are going with forge? With this issue and #10?

**Comment by ItsBlackGear** [comment]
in other news, this can be closed since i did a small rollback onto a feature that caused many incompat issues, and that allowed simply improved terrain generation to get back to normal! c: i'll release the update today
