### ISSUE TITLE
Long distance terrain checks in structures crashes (With Repurposed Structures 1.17.1)

### ISSUE THREAD

**Issue by TelepathicGrunt** [KdotJPG/Simply-Improved-Terrain#18]
Hello! Someone seemed to have found an issue with my mod Repurposed Structures and your SimplyImprovedTerrain mod
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/135

Basically, it seems SImplyImprovedTerrain doesn't like me trying to get the height of terrain 70 blocks away here:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/latest-released/src/main/java/com/telepathicgrunt/repurposedstructures/world/structures/MineshaftEndStructure.java#L44

The crash is this about the internals of NoiseChunkGenerator returning a null value when Minecraft normally wouldn't return a null
https://paste.ee/p/LzgI8

I'm not too keen on this kind of internal stuff but is this something you'll be able to fix or your end? If not, I may be able to turn off my long distance checking if SimplyImprovedTerrain is on.

**Comment by KdotJPG** [comment]
Interesting. My first thought is if I messed something up with the biome blending cache. Maybe some race condition I didn't properly account for. Or perhaps I need to do something more than call callbackInfoReturnable.cancel() on this line https://github.com/KdotJPG/Simply-Improved-Terrain/blob/4b9ca9e470eea9fadd1c16ae812198e98106e805/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinNoiseChunkGenerator.java#L171

Hoping this is a quick fix!

**Comment by TelepathicGrunt** [comment]
looks like it was fixed in v0.4.0.3 simply improved terrain. I almost forgot about this issue lol. And I didnt realized an updated came out. i'll close this now
