### ISSUE TITLE
Instant Crash Incompatibility while loading with RoadRunner

### ISSUE THREAD

**Issue by Reshirou** [KdotJPG/Simply-Improved-Terrain#22]
No crash log, just instant crash before getting to main menu when running with ONLY SIT and RoadRunner in the mods folder

Here is a link to RoadRunner https://www.curseforge.com/minecraft/mc-mods/roadrunner

It's the Forge fork version of Lithium, which I see was incompatible with SIT in a previous Fabric version but got fixed

**Comment by KdotJPG** [comment]
I'll take a look at this for the next release. Hopefully I'll just need to mirror the fabric `lithium:options` JSON entry.

**Comment by MagmaSlime123** [comment]
> I'll take a look at this for the next release. Hopefully I'll just need to mirror the fabric `lithium:options` JSON entry.

Still waiting for a fix.
