### ISSUE TITLE
Incompatibility with aerial hell

### ISSUE THREAD

**Issue by ghost** [KdotJPG/Simply-Improved-Terrain#24]
Mod Link;
[Aerial Hell](https://www.curseforge.com/minecraft/mc-mods/aerial-hell)
crashes on dim gen
logs and what not:
[message.txt](https://github.com/KdotJPG/Simply-Improved-Terrain/files/10711292/message.txt)
[debug-4.log](https://github.com/KdotJPG/Simply-Improved-Terrain/files/10711303/debug-4.log)
[2023-02-09-4.log](https://github.com/KdotJPG/Simply-Improved-Terrain/files/10711306/2023-02-09-4.log)

**Comment by KdotJPG** [comment]
Uploaded version 0.3.3 with the fix. Should show up on curseforge soon.

EDIT: https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain/files/4469933
