### ISSUE TITLE
Crashes with Roadrunner.

### ISSUE THREAD

**Issue by MagmaSlime123** [KdotJPG/Simply-Improved-Terrain#25]
Title. If this is dead (it seem like it), please remove it.

![image](https://user-images.githubusercontent.com/51277766/219555205-58dfe928-eb2b-4d8d-8c6a-a28ad68b272d.png)

https://pastebin.com/WcYJC00q

**Comment by KdotJPG** [comment]
~~Hmm, are you sure this is related to this mod? I see this in the crashlog:~~

```
	Mod File: create-mc1.16.5_v0.3.2g.jar
	Failure message: Mod create requires flywheel 1.16-0.2.3 or above, and below 1.16-0.3
		Currently, flywheel is not installed
	Mod Version: v0.3.2g
	Mod Issue URL: https://github.com/Creators-of-Create/Create/issues
	Exception message: MISSING EXCEPTION MESSAGE
```

Replicated. I also see that it's the same issue as #22.

**Comment by KdotJPG** [comment]
Uploaded version 0.3.3 with the fix. Should show up on curseforge soon.

EDIT: it's up! https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain/files/4469933

I cleared the comment from #23 where you asked me to check this project's issues, to keep it more topic-focused, but will make a better effort to keep up with issues here going forward.

Let me know if any further problems arise!
