### ISSUE TITLE
[1.20.1] Crash on server startup with latest version

### ISSUE THREAD

**Issue by BugmanBugman** [KdotJPG/Simply-Improved-Terrain#28]
https://hastebin.com/share/ocetegewuc.php

**Comment by KdotJPG** [comment]
The link seems to be broken. Would you be able to create another? Thanks!

**Comment by BugmanBugman** [comment]
Sadly I don't have access to my computer rn, but anyone should be able to recreate it by running the latest version in a modpack or server environment
________________________________

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/13fb5a3ceb19c7925a2e1e313c894175

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/57e9c53345cd564e7e9ac43cacc3b677 Got this too, might be due to structure gels?

**Comment by Rhayn31** [comment]
I'm having the same issue out of the blue.

https://pastebin.com/Rt4YJZYK

**Comment by KdotJPG** [comment]
Right, yes, this error. I suspect this was similar to the one another user experienced with Amplified Nether. I've uploaded 0.5.2.0 to CurseForge which includes some fixes relating to this. It should show up shortly.

The mod list helps a lot too, thanks!

**Comment by BugmanBugman** [comment]
Getting a new crash with the mod on the latest version
https://gist.github.com/BugmanBugman/621e80c90d2e952244e441c2fb06a64c

**Comment by KdotJPG** [comment]
Looks to be a conflict between
https://github.com/KdotJPG/Simply-Improved-Terrain/blob/1.20/common/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinBlueIceFeature.java
and
https://github.com/MCTeamPotato/Redirector/blob/87bb999ea434f7d6f3b44f5f28d636e465f7d824/common/src/main/java/com/teampotato/redirector/mixin/net/minecraft/world/level/levelgen/feature/BlueIceFeatureMixin.java

Looks like I may need to refactor this mixin as well.

**Comment by BugmanBugman** [comment]
Took out redirectioner, it still happens
https://gist.github.com/BugmanBugman/56cb8d998f29d0e6032453686862a8aa
My 304 mods:
	- achiopt 1.0.2
	- adaptive_performance_tweaks_core 10.2.0
	- adaptive_performance_tweaks_gamerules 10.0.0
	- adaptive_performance_tweaks_items 10.0.0
	- adaptive_performance_tweaks_player 10.0.0
	- advancementframes 1.20-2.1.0
	- advancementplaques 1.5.1
	- aiimprovements 0.5.2
	- airhop 8.0.0
	- alexscaves 1.0.9
	- alexsmobs 1.22.6
	- amplifiednether 1.2.3
	- apotheosis 7.1.0
	- apotheotic_additions 1.2.0.1
	- appleskin 2.5.1+mc1.20.1
	- aquamirae 6.API15
	- architectury 9.1.12
	- armor_weight 1.0.1
	- armored_redstone 1.20.1-0.4.0
	- artifacts 9.2.0
	- astikorcarts 1.1.6
	- asynclocator 1.3.0
	- attributefix 21.0.4
	- attributeslib 1.2.1
	- bagofholding 8.0.1
	- bagus_lib 1.20.1-4.2.1
	- bagusmob 1.20.1-3.1.1
	- balm 7.2.1
	- bcc 4.0.8
	- beaconsforall 6.2.1+1.20.1
	- beefix 1.0.7
	- beekeeperhut 1.3.0
	- bestylewither 1.6.0
	- better_beacons 1.0.2
	- better_totem_of_undying 1.1.0
	- betterburning 9.0.2
	- betterchunkloading 1.20.1-2.5
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterendisland 1.20-Forge-2.0.4
	- betterfortresses 1.20-Forge-2.0.5
	- bettergolem 1.20.1-4.0.0
	- betterinvisibility 1.0.4
	- betterjukebox 1.20-1.3
	- betterjungletemples 1.20-Forge-2.0.4
	- betterlily 1.20-1.3.1
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- bfendcities 1.0
	- bigbrain 1.20-1.7.3
	- biomemakeover 1.20.1-1.11.4
	- blueprint 7.0.0
	- bookshelf 20.1.6
	- born_in_chaos_v1 1.0.0
	- bosses_of_mass_destruction 1.0.6
	- bountiful 6.0.3+1.20.1
	- brutalbosses 1.20.1-6.6
	- bygonenether 1.3.2
	- cant_sleep_clowns_will_eat_me 1.1.0.1
	- carpeted 1.20-1.4
	- cataclysm 1.0
	- cave_dweller 1.6.5
	- chefsdelight 1.0.3-forge-1.20.1
	- chunksending 1.20.1-2.8
	- chunky 1.3.92
	- citadel 2.4.9
	- cloth_config 11.1.106
	- cloudstorage 1.4.0
	- collective 7.16
	- combat_next 1.20.1-1.0.2
	- conjurer_illager 1.1.6
	- connectivity 1.20.1-4.9
	- corgilib 4.0.0.4
	- coroutil 1.20.1-1.3.3
	- corpse 1.20.1-1.0.9
	- cotw 1.0.0
	- crashutilities 8.1.4
	- creativecore 2.11.14
	- creeperheal 2.0.3
	- creeperoverhaul 3.0.1
	- cupboard 1.20.1-2.1
	- curios 5.4.5+1.20.1
	- cyanide 4.1.0
	- deathfinder 8.0.1
	- deathknell 10.0.3
	- deathquotes 3.3
	- deuf 1.20.1-1.3
	- dmmttba 1.0.2
	- does_potato_tick 1.20.1-3.7.0
	- domesticationinnovation 1.7.1
	- doubledoors 5.1
	- dragonmounts 1.1.5.b3
	- dummmmmmy 1.20-1.8.13
	- dungeoncrawl 2.3.14
	- dungeons_arise 2.1.57-1.20.1
	- dusk 1.20.1-3.5
	- dynamo 1.0.0
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.1
	- echochest 8.0.0
	- ecologics 2.2.0
	- eeeabsmobs 0.3
	- enchantwithmob 1.20.1-11.4.1
	- ender_chested 1.1.0
	- endermanoverhaul 1.0.3
	- endersdelight 1.0.3
	- endertrigon 1.0
	- enderzoology 8.0.1
	- enemyexpansion 2.0.0
	- enhancedcelestials 5.0.0.2
	- everycomp 1.20-2.6.18
	- expandability 9.0.0
	- experiencebugfix 46.2.2
	- experienced_crops 1.20.1-1.1.0
	- explorify 1.3.0-mc1.20
	- extra_compat 1.3.8
	- eyesinthedarkness 1.3.10
	- fabrication 3.4.5+1.20
	- farlanders 1.4.1
	- farmersdelight 1.20.1-1.2.3
	- fastbench 8.0.2
	- fastfurnace 8.0.1
	- fastpaintings 1.20-1.2.3
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- flatbedrock 3.0.1-build.18+mc1.20.1
	- flib 0.0.11
	- flowerymooblooms 2.0.0
	- footprintparticle 0.4.0-mc1.20
	- forge 47.2.17
	- forgeconfigscreens 8.0.2
	- framework 0.6.16
	- friendsandfoes 2.0.4
	- ftbbackups2 1.0.23
	- functionalarmortrim 4
	- geckolib 4.3.1
	- goated 1.20-1.3.4
	- goblintraders 1.9.3
	- golemsarefriends 1.20.0-1.0.1
	- grassnotfloating 0.1.0
	- grimoireofgaia 4.0.0-alpha.5
	- guardvillagers 1.20.1-1.6.3
	- habitat 1.2.5
	- hardcorerevival 12.0.1
	- harvestwithease 8.0.0.2
	- hauntedharvest 1.20-3.1.16
	- heartbalance 1.0.2
	- hearths 1.0.0-mc1.20u1.20.1
	- heartstone 1.20-1.3.0
	- hmag 9.0.7
	- hourglass 1.2.1.1
	- hunters_return 1.20.1-11.2.0
	- iceberg 1.1.18
	- illagerinvasion 8.0.3
	- inventorysorter 23.0.1
	- irons_rpg_tweaks 1.20-1.2.1
	- iswydt 1.0.2
	- jearchaeology 1.20.1-1.0.3
	- jeed 1.20-2.1.6
	- jei 15.2.0.27
	- jepp 1.20-1.1.2
	- jeresources 1.4.0.238
	- just_enough_beacons 1.1.1
	- justenoughbreeding 1.0.10
	- justenoughprofessions 3.0.1
	- kambrik 6.1.1+1.20.1
	- kiwi 11.1.1
	- kobolds 2.10.1
	- kotlinforforge 4.8.0
	- krypton 0.2.3
	- labels 1.20-1.19
	- lava_monster 1.0.11
	- leaky 1.20.1-1.7
	- leavesbegone 8.0.0
	- legends_gather 1.20.1-2.0.0
	- libertyvillagers 2.0.0+forge+1.20.1
	- limitedchunks 1.8
	- littlelogistics 1.20.1.2
	- logbegone 1.0.9
	- lootintegrations 1.20.1-3.4
	- majruszlibrary 7.0.2
	- majruszsaccessories 1.4.0
	- majruszsdifficulty 1.9.3
	- majruszsenchantments 1.10.5
	- map_atlases 1.20-5.12.5
	- maxhealthfix 12.0.2
	- memoryleakfix 1.1.2
	- memorysweep 1.0.0
	- metalbundles 8.0.1
	- minecraft 1.20.1
	- miners_delight 1.20.1-1.2
	- mixinextras 0.2.0
	- mixinsquared 0.1.1
	- mobcaptains 2.1.2
	- mobcrossing 1.0.0
	- mobpc 1.0.0
	- moderately_enough_effect_desc 1.0.0
	- modernfix 5.10.1+mc1.20.1
	- moonlight 1.20-2.8.67
	- mountedpearl 1.0.1
	- moyai 1.20-2.1.4
	- mr_logical_dyemixing 1.0.0
	- mutantmonsters 8.0.6
	- mysticaloaktree 1.20-1.11
	- nanhealthfixer 1.20.1-0.0.1
	- neruina 1.3.0
	- netherchested 8.0.1
	- netherportalfix 13.0.1
	- nethersdelight 1.20.1-4.0
	- nightconfigfixes 8.0.0
	- normaldamage 1.0.0-forge
	- notenoughcrashes 4.4.6+1.20.1
	- nullscape 1.2.4
	- nyfsspiders 2.1.1
	- obscure_api 15
	- oceansdelight 1.0.2-1.20
	- overweight_farming 1.20.1-2.1.0-forge
	- packetfixer 1.1.7
	- parry 2.5.0
	- patchouli 1.20.1-83-FORGE
	- paxi 1.20-Forge-4.0
	- piglinproliferation 1.20-1.1.2
	- placebo 8.6.0
	- polylib 2000.0.3-build.97
	- polymorph 0.49.2+1.20.1
	- portablehole 8.0.0
	- prism 1.0.5
	- puzzlesaccessapi 8.0.7
	- puzzlesapi 8.1.4
	- puzzleslib 8.1.11
	- queen_bee 3.1.3
	- radium 0.12.2+git.5f80f74
	- ragnagoblin 2.0.0
	- raided 0.1.3
	- ramel 1.0.1
	- randomium 1.20-1.29
	- rats 1.20.1-8.1.2
	- ravageandcabbage 1.2.3
	- readyplayerfun 1.20.1-2.8.0.0-FORGE
	- recipeessentials 1.20.1-3.2
	- regrowth 46.31.2
	- relics_and_alchemy 1.20.1-0.7.1
	- repurposed_structures 7.1.11+1.20.1-forge
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.19
	- respawninganimals 8.1.1
	- responsiveshields 2.3
	- revampedwolf 1.20.1-5.0.0
	- salju_ladders 2.4.3
	- searchables 1.0.2
	- secondchanceforge 1.5.1
	- shutdowner 2.0
	- simplyimprovedterrain 1.20.1-0.5.2.0-alpha
	- sleep_tight 1.20-1.1.12
	- slimyboyos 7.0.0.4
	- smarterfarmers 1.20-1.7.3
	- smoothboot 0.0.3
	- smoothchunk 1.20.1-3.5
	- snifferent 1.0.3
	- snowrealmagic 9.1.2
	- snowyspirit 1.20-2.2.6
	- spark 1.10.53
	- sparsestructuresreforged 1.19.2-1.20.1-0.0.3
	- spawnbalanceutility 46.13.3
	- species 1.20.1-1.3
	- spectrelib 0.13.14+1.20.1
	- spelunkery 1.20.1-0.3.4
	- starlight 1.1.2+forge.1cda73c
	- strongersnowballs 13.0.2
	- structure_gel 2.15.1
	- structureessentials 1.20.1-3.2
	- sullysmod 3.0.1-beta
	- supernatural 2.9.3
	- supplementaries 1.20-2.7.7
	- suppsquared 1.20-1.1.11
	- tact 1.0.6
	- taniwha 1.20.0-5.4.4
	- tinyskeletons 8.0.1
	- tramplenomore 13.0.2
	- treasuredistance 1.20-1.2
	- treechop 0.18.3
	- trenzalore 3.3.10
	- universalbonemeal 8.0.1
	- universalenchants 8.0.0
	- usefulspyglass 0.5.0
	- v_slab_compat 1.20-2.0
	- veinmining 1.2.1+1.20.1
	- villagersplus 3.0
	- villagersrespawn 46.7.0
	- villagesandpillages 1.0.0
	- villainousfishai 1.1
	- visualworkbench 8.0.0
	- watut 1.20.1-1.0.11
	- wealthy_and_growth 1.20.1-3.1.0
	- weaponmaster 3.0.6
	- weather2 1.20.1-2.8.1
	- whatthebucket 11.0.3
	- yungsapi 1.20-Forge-4.0.2
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3
	- zillagersweararmor 1.20-1.3.1

**Comment by KdotJPG** [comment]
I've started debugging using All The Mods 9, at least, and found that the first conflict is in the `LakeFeature` mixin (seemingly versus `structure_gel`). I'm going to work through these, then compare its mods with this list to make sure I'm not missing anything. Is there a particular modpack your list is based off of, or is it manually put together?

The error you're getting is interestingly generic, but I'm hoping I can reproduce it at some point in this process.

Thanks for including the list!

**Comment by BugmanBugman** [comment]
Just removed structure gel from my pack and it seems to work! Yeah the incompatibility seems to be with that

**Comment by KdotJPG** [comment]
Just posted version 0.5.3.0 which solves the incompatibility with both of those two mods.

**Comment by KdotJPG** [comment]
Looks like the issue here is resolved. Feel free to re-open the issue if the same thing pops up from this version out.

**Comment by BugmanBugman** [comment]
Thank you Kdot :) hope you had a good Christmas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
