### ISSUE TITLE
Mixin conflict with Repurposed Structures

### ISSUE THREAD

**Issue by SmittyTheGod** [KdotJPG/Simply-Improved-Terrain#29]
There is a conflict between the two

**Comment by KdotJPG** [comment]
Re: the discussion in https://github.com/TelepathicGrunt/RepurposedStructures/issues/308 the fix will occur here. Thanks for the find!

**Comment by KdotJPG** [comment]
Fix included in 0.5.2.0 as well as in the latest Repurposed Structures.
