### ISSUE TITLE
Simply Improved Terrain causes nether dimension to be glitched out

### ISSUE THREAD

**Issue by BugmanBugman** [KdotJPG/Simply-Improved-Terrain#4]
![2021-05-10_12 28 16](https://user-images.githubusercontent.com/40730042/117701810-4a4d0a00-b18d-11eb-815b-4fa59e97813c.png)
![2021-05-10_12 27 50](https://user-images.githubusercontent.com/40730042/117701816-4c16cd80-b18d-11eb-9c03-78471ea28069.png)
![2021-05-10_12 27 54](https://user-images.githubusercontent.com/40730042/117701817-4caf6400-b18d-11eb-9cd8-fe9fd3a0a76e.png)
![2021-05-10_12 28 08](https://user-images.githubusercontent.com/40730042/117701819-4caf6400-b18d-11eb-9f55-ff5009889412.png)
Not  sure if this is happening to anyone else, but the mod is just tearing up the nether dimension for some reason

**Comment by KdotJPG** [comment]
Odd. Not seeing this on my end. Testing with the latest version I have uploaded to CurseForge. Minecraft 1.16.5-forge-3.6.10
![image](https://user-images.githubusercontent.com/8829856/117728286-42a25b00-b1b7-11eb-8fc8-eb01db3d9dd8.png)

Do you have any datapacks or other mods installed alongside it? Could you tell me the Minecraft version, Forge version, and the world seed?

**Comment by BugmanBugman** [comment]
Found the conflict! It seems to be the overworld two mod...strange
https://www.curseforge.com/minecraft/mc-mods/overworld-two-forge

**Comment by KdotJPG** [comment]
I see. This would make sense, as Overworld Two seems to change the GenerationShapeConfig in a manner intended to only be compatible with its other changes which themselves on the Vanilla terrain noise interpolation. When mine overwrites this, it reads Overworld Two's GenerationShapeConfig which contains data not well suited for either pure Vanilla or Simply Improved Terrain generation code.

This is unfortunately one category of mod for which it is difficult to enable compatibility without introducing special cases. Anything that depends on Vanilla noise interpolation will either be overshadowed or break something, depending on the changes the other mod makes.

If it helps to choose between the two, Overworld Two seems to focus more on creating different terrain features, while Simply Improved Terrain focuses on overhauling the appearance of existing features. OW2 still has visible grid patterns and hills with angle bias, while SIT doesn't change the underlying terrain formula quite as much.

**Comment by BugmanBugman** [comment]
For sure I’ll stick with this one since the terrain looks far better, especially with Quark’s realistic world type. I mainly had OW2 on since it had a feature that would improve performance on all world types, hopefully it will be able to be sorted out soon
