### ISSUE TITLE
[Suggestion] getting rid of the floating chunks and blocks in overworld/nether generation

### ISSUE THREAD

**Issue by BugmanBugman** [KdotJPG/Simply-Improved-Terrain#5]
If this is out of scope for this mod, I completely understand, I was just wondering if this mod would be able to fix the weird floating blocks that happens in vanilla MC.
![2021-05-10_11 22 49](https://user-images.githubusercontent.com/40730042/118374959-3e45bb80-b584-11eb-9992-d82a247589b5.png)
![2021-05-12_15 38 13](https://user-images.githubusercontent.com/40730042/118374961-400f7f00-b584-11eb-9144-70ffe91c1c50.png)
![2021-05-12_15 38 29](https://user-images.githubusercontent.com/40730042/118374962-4140ac00-b584-11eb-977f-53648511432d.png)
![2021-05-12_23 10 49](https://user-images.githubusercontent.com/40730042/118374963-4271d900-b584-11eb-82aa-f80b43484da9.png)
![2021-05-15_00 02 23](https://user-images.githubusercontent.com/40730042/118374964-430a6f80-b584-11eb-9bf3-e59b4659df76.png)
![2021-05-15_00 02 28](https://user-images.githubusercontent.com/40730042/118374966-43a30600-b584-11eb-8700-eaae04878c05.png)

**Comment by KdotJPG** [comment]
Yep, this does happen, in various forms in both Vanilla generation and Simply Improved Terrain. I don't know if it would be in scope for this mod, or if it would be better suited as a separate mod that could be bundled with whatever. It would be straightforward to remove floating islands of diameter up to 15 blocks, though.

To do this, a mod could add a pass somewhere in the generation pipeline where there is access to the current chunk's terrain noise shape + all of its neighbors, then check for + remove shapes that don't connect with the main ground but have the aforementioned max diameter.

The diameter constraint would be to ensure unbiased culling regardless of offset relative to chunk borders or rotation, and avoid generation inconsistencies that result in chunk border cutoffs at the same time. Could probably also get away with just a max width check, or maybe a compromise between the two. It would be interesting to compare the results in different terrain gens, which islands get removed or left behind.

I might implement this at some point. Unsure if it will be in this mod or somewhere else. It probably wouldn't be able to be in the immediate future though.
