### ISSUE TITLE
[Bug Report] Fabric - Incompatibility with Lithium

### ISSUE THREAD

**Issue by Abbanon** [KdotJPG/Simply-Improved-Terrain#7]
The game crashes on startup when using the Fabric release of this mod alongside latest Lithium.
I've consulted with the CaffeineMC team, and apparently it's a Mixin conflict.
Log: https://paste.ee/p/cyDCS

**Comment by QPCrummer** [comment]
I think it is fixed in the latest release

**Comment by KdotJPG** [comment]
Fixed in version 0.3.2.1-Fabric! https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain/files

https://github.com/KdotJPG/Simply-Improved-Terrain/pull/6
