### ISSUE TITLE
No se generan las estructuras del DUNGEONS CRAWL

### ISSUE THREAD

**Issue by d-rick** [KdotJPG/Simply-Improved-Terrain#8]
El mundo se abre pero no se genera ninguna estructura del mod "DUNGEONS CRAWL" Y EL COMANDO \locate   no encuentra ninguna estructura de ese mod especifico. en forge

**Comment by KdotJPG** [comment]
¿Qué versiones del mods? Tengo estas, y la estructura genera.

![image](https://user-images.githubusercontent.com/8829856/119056096-1c8b7080-b998-11eb-872b-7032e191f235.png)
![image](https://user-images.githubusercontent.com/8829856/119056113-21502480-b998-11eb-90d1-56944825ce0e.png)
